import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { colors } from '../theme/colors';

export default function LoginScreen({ navigation }) {
  const { login } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit() { setError(''); if (!email.trim() || !password) return setError('Email and password are required.'); setLoading(true); try { await login(email.trim(), password); } catch (err) { setError(err.response?.data?.error || 'Unable to sign in. Please try again.'); } finally { setLoading(false); } }
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>‹ Back</Text></TouchableOpacity><Text style={styles.eyebrow}>WELCOME BACK</Text><Text style={styles.title}>Sign in to CareSignal</Text><Text style={styles.subtitle}>Continue your care journey securely.</Text><View style={styles.form}><Field label="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="you@example.com" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry placeholder="Your password" />{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity disabled={loading} onPress={submit} style={styles.primary}><Text style={styles.primaryText}>{loading ? 'Signing in...' : 'Sign in'}</Text></TouchableOpacity></View><View style={styles.footer}><Text style={styles.footerText}>New to CareSignal?</Text><TouchableOpacity onPress={() => navigation.navigate('Register')}><Text style={styles.link}> Create an account</Text></TouchableOpacity></View></ScrollView></KeyboardAvoidingView>;
}
function Field({ label, ...props }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} placeholderTextColor="#94A3B8" {...props} /></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.mist }, content: { padding: 28, paddingTop: 58, flexGrow: 1 }, back: { color: colors.ocean, fontSize: 16, fontWeight: '800' }, eyebrow: { color: colors.ocean, fontSize: 12, fontWeight: '800', letterSpacing: 2, marginTop: 58 }, title: { color: colors.ink, fontSize: 34, lineHeight: 40, fontWeight: '800', marginTop: 12 }, subtitle: { color: colors.slate, fontSize: 16, marginTop: 10 }, form: { marginTop: 38 }, field: { marginBottom: 18 }, label: { color: colors.ink, fontSize: 14, fontWeight: '800', marginBottom: 8 }, input: { backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 15, color: colors.ink, fontSize: 16 }, primary: { backgroundColor: colors.ink, padding: 17, borderRadius: 12, alignItems: 'center', marginTop: 6 }, primaryText: { color: colors.white, fontSize: 16, fontWeight: '800' }, error: { color: colors.danger, backgroundColor: colors.dangerBg, padding: 13, borderRadius: 10, marginBottom: 14, lineHeight: 20 }, footer: { flexDirection: 'row', justifyContent: 'center', marginTop: 'auto', paddingTop: 40 }, footerText: { color: colors.slate }, link: { color: colors.ocean, fontWeight: '800' } });
