import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { colors } from '../theme/colors';

export default function RegisterScreen({ navigation }) {
  const { register } = useAuth(); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  function update(name, value) { setForm({ ...form, [name]: value }); setError(''); }
  async function submit() { setError(''); if (!form.name.trim() || !form.email.trim() || !form.password) return setError('Name, email, and password are required.'); if (!/^\S+@\S+\.\S+$/.test(form.email)) return setError('Enter a valid email address.'); if (form.password.length < 8) return setError('Password must be at least 8 characters.'); setLoading(true); try { await register(form.name.trim(), form.email.trim(), form.password); } catch (err) { setError(err.response?.data?.error || 'Unable to create your account.'); } finally { setLoading(false); } }
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>‹ Back</Text></TouchableOpacity><Text style={styles.eyebrow}>GET STARTED</Text><Text style={styles.title}>Create your patient account</Text><Text style={styles.subtitle}>A secure place to begin your CareSignal journey.</Text><View style={styles.form}><Field label="Full name" value={form.name} onChangeText={(v) => update('name', v)} placeholder="Your name" /><Field label="Email address" value={form.email} onChangeText={(v) => update('email', v)} keyboardType="email-address" autoCapitalize="none" placeholder="you@example.com" /><Field label="Password" value={form.password} onChangeText={(v) => update('password', v)} secureTextEntry placeholder="At least 8 characters" /><Text style={styles.helper}>Use at least 8 characters. Avoid including your name or email username.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity disabled={loading} onPress={submit} style={styles.primary}><Text style={styles.primaryText}>{loading ? 'Creating account...' : 'Create account'}</Text></TouchableOpacity></View><View style={styles.footer}><Text style={styles.footerText}>Already registered?</Text><TouchableOpacity onPress={() => navigation.navigate('Login')}><Text style={styles.link}> Sign in</Text></TouchableOpacity></View></ScrollView></KeyboardAvoidingView>;
}
function Field({ label, ...props }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} placeholderTextColor="#94A3B8" {...props} /></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.mist }, content: { padding: 28, paddingTop: 58, flexGrow: 1 }, back: { color: colors.ocean, fontSize: 16, fontWeight: '800' }, eyebrow: { color: colors.ocean, fontSize: 12, fontWeight: '800', letterSpacing: 2, marginTop: 42 }, title: { color: colors.ink, fontSize: 34, lineHeight: 40, fontWeight: '800', marginTop: 12 }, subtitle: { color: colors.slate, fontSize: 16, marginTop: 10 }, form: { marginTop: 32 }, field: { marginBottom: 18 }, label: { color: colors.ink, fontSize: 14, fontWeight: '800', marginBottom: 8 }, input: { backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 15, color: colors.ink, fontSize: 16 }, helper: { color: colors.slate, fontSize: 12, lineHeight: 18, marginTop: -8, marginBottom: 14 }, primary: { backgroundColor: colors.ink, padding: 17, borderRadius: 12, alignItems: 'center' }, primaryText: { color: colors.white, fontSize: 16, fontWeight: '800' }, error: { color: colors.danger, backgroundColor: colors.dangerBg, padding: 13, borderRadius: 10, marginBottom: 14, lineHeight: 20 }, footer: { flexDirection: 'row', justifyContent: 'center', marginTop: 'auto', paddingTop: 38 }, footerText: { color: colors.slate }, link: { color: colors.ocean, fontWeight: '800' } });
