import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import axiosClient from '../api/axiosClient';
import Navbar from '../components/Navbar';

function formatDate(value) { return value ? new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : 'Not recorded'; }

export default function PatientList() {
  const [patients, setPatients] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { axiosClient.get('/api/patients').then(({ data }) => setPatients(data)).catch((err) => setError(err.response?.data?.error || 'Unable to load patients.')).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => patients.filter((patient) => `${patient.name} ${patient.email} ${patient.phone || ''}`.toLowerCase().includes(query.toLowerCase())), [patients, query]);
  return <div className="min-h-screen bg-mist"><Navbar /><main className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-ocean">Directory</p><h1 className="mt-2 font-display text-4xl font-bold text-ink">Patients</h1><p className="mt-3 text-slate-500">{patients.length} patient profiles available for review.</p></div><label className="relative block sm:w-80"><span className="sr-only">Search patients</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, email, phone" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none transition focus:border-ocean focus:ring-4 focus:ring-teal-50" /></label></div>{error && <div className="mt-8 rounded-xl border border-red-100 bg-red-50 px-5 py-4 text-sm font-semibold text-red-700">{error}</div>}<section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-soft">{loading ? <div className="p-12 text-center text-slate-500">Loading patient directory...</div> : filtered.length === 0 ? <div className="p-12 text-center"><p className="font-display text-xl font-bold text-ink">No matching patients</p><p className="mt-2 text-sm text-slate-500">Try a different search term.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="border-b border-slate-200 bg-slate-50"><tr><th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">Patient</th><th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">Date of birth</th><th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">Phone</th><th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">Record</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((patient) => <tr key={patient.id} className="transition hover:bg-mist"><td className="px-6 py-5"><strong className="block text-sm text-ink">{patient.name}</strong><span className="text-xs text-slate-500">{patient.email}</span></td><td className="px-6 py-5 text-sm text-slate-600">{formatDate(patient.date_of_birth)}</td><td className="px-6 py-5 text-sm text-slate-600">{patient.phone || 'Not recorded'}</td><td className="px-6 py-5"><Link to={`/patients/${patient.id}`} className="text-sm font-bold text-ocean hover:text-ink">View record →</Link></td></tr>)}</tbody></table></div>}</section></main></div>;
}
